image: python:latest

stages:
 - Build
 - Dynamic Application Security Testing 
 - Deploy


services:
  - docker:dind 
  

owasp:
   image: docker:latest
   stage: Dynamic Application Security Testing

   script:
     - echo 'hello!'
     - docker run -t owasp/zap2docker-stable zap-baseline.py -t ${URL2}
   allow_failure: true


build:
   image: docker:latest
   stage: Build

   script:
      - "docker build -t ${CI_REGISTRY_USER}/somativa2:latest ."
      - "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}"
      - "docker push ${CI_REGISTRY_USER}/somativa2:latest"

deploy:
  image: ubuntu:latest
  stage: Deploy

  script:
     - 'echo "Building docker!"'
     - apt-get update -qq
     - 'which ssh-agent || ( apt-get install -qq openssh-client )'
     - eval $(ssh-agent -s)
     - ssh-add <(echo "$SSH_PRIVATE_KEY")
     - mkdir -p ~/.ssh
     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  
     - echo "Deploy project on server"
     - ssh $DEPLOY_HOST "docker pull ${CI_REGISTRY_USER}/somativa2:latest"
     - ssh $DEPLOY_HOST "docker stop app3"
     - ssh $DEPLOY_HOST "docker run --rm -d --name app3 -p $APP_PORT:$APP_PORT ${CI_REGISTRY_USER}/somativa2:latest"

   
   
   
